openapi: 3.0.1
info:
  title: API Cupones Xoltex
  version: "1.0"
paths:
  /cupones:
    get:
      summary: Obtener todos los cupones
      responses:
        '200':
          description: Lista de cupones
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:lambda-cupones/invocations
        httpMethod: POST
        type: aws_proxy