openapi: 3.0.1
info:
  title: API Test Clientes
  version: "1.0"
paths:
  /clientes:
    get:
      summary: Obtener clientes
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:lambda-clientes/invocations
        httpMethod: POST
        type: aws_proxy
 