openapi: 3.0.1
info:
  title: API Usuarios Xoltex
  version: "1.0"
paths:
  /usuarios:
    get:
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:lambda-usuarios/invocations
        httpMethod: POST
        type: aws_proxy