name: Test API Workflow Trigger

on:
  push:
    branches:
      - main
    paths:
      - '*.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Debug paso inicial
        run: echo "✅ Workflow disparado correctamente"